---
- name: Install Mongo
  hosts: all
  become: true
  tasks:
    - name: Add an apt key by id from a keyserver
      apt_key:
        id: EA312927
        keyserver: keyserver.ubuntu.com

    - name: Add apt repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    - name: Enable mongod.service
      systemd:
        name: mongod
        enabled: yes
